version: '3'

volumes:
  jenkins_home:
    external: true

services:
  jenkins:
    image: docker.io/blankia/jenkins:latest
    build:
      context: .
      args:
        DOCKER_GID: ${DOCKER_GID}
    volumes:
      - jenkins_home:/var/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"